[project]
name = "odoo-addons-oca-operating-unit"
version = "18.0.20250102.0"
dependencies = [
    "odoo-addon-operating_unit==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
